version: "2"

services:

  namenode:
    image: uhopper/hadoop-namenode:2.8.1
    network_mode: host
    volumes:
      - ./namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop-cluster

  datanode1:
    image: uhopper/hadoop-datanode:2.8.1
    network_mode: host
    volumes:
      - ./datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  zk:
    image: jplock/zookeeper:3.4.5
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  master:
    image: mesosphere/mesos-master-hdfs:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - ./mesos-master-workdir:/tmp/mesos
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave-hdfs:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - ./mesos-slave-workdir:/tmp/mesos
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk